import{projectFiles}from'./project-files-data.js';
const panel=document.querySelector('[data-project-files]');
if(panel){
 const id=new URLSearchParams(location.search).get('id'),tabs=[...document.querySelectorAll('main [role=tab]')],panels=tabs.map(t=>document.getElementById(t.getAttribute('aria-controls'))),status=panel.querySelector('[data-project-files-status]');
 const initialProjects=JSON.parse(document.getElementById('ceobe-projects-data').textContent),initialChats=JSON.parse(document.getElementById('ceobe-chat-catalog').textContent),initialAssets=JSON.parse(document.getElementById('ceobe-assets-data').textContent);let generation=0;
 function tab(index,push=false){for(const [i,t]of tabs.entries()){t.dataset.state=i===index?'active':'inactive';t.setAttribute('aria-selected',String(i===index));t.tabIndex=i===index?0:-1;panels[i].hidden=i!==index;panels[i].dataset.state=i===index?'active':'inactive'}if(push){const u=new URL(location.href);if(index)u.searchParams.set('tab','files');else u.searchParams.delete('tab');history.pushState(null,'',u)}}
 const requested=()=>['files','sources'].includes(new URLSearchParams(location.search).get('tab'))?1:0;
 for(const [i,t]of tabs.entries()){t.addEventListener('click',()=>tab(i,true));t.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?1:1-i;tab(next,true);tabs[next].focus()}})}window.addEventListener('popstate',()=>tab(requested()));tab(requested());if(new URLSearchParams(location.search).get('tab')==='sources'){const u=new URL(location.href);u.searchParams.set('tab','files');history.replaceState(null,'',u)}
 function render(projects,chats,assets,snapshot=false){const project=projects.find(p=>p.id===id);window.ceobeProjectFiles=projectFiles(assets,project,chats);document.dispatchEvent(new CustomEvent('ceobe:project-files',{detail:{items:window.ceobeProjectFiles}}));status.textContent=!project?'项目不存在，未显示任何文件。':snapshot?'当前显示只读快照，无法确认最新聊天与文件；恢复本地服务后刷新。':'仅统计本项目聊天中的文件；聊天移入或移出后自动更新，不复制或删除原文件。'}
 async function load(){const token=++generation;try{const responses=await Promise.all(['/api/projects','/api/chats','./assets-index.json'].map(url=>fetch(url,{cache:'no-store'})));if(responses.some(r=>!r.ok))throw Error();const [p,c,a]=await Promise.all(responses.map(r=>r.json()));if(!Array.isArray(p.projects)||!Array.isArray(c.conversations)||!Array.isArray(a))throw Error();if(token===generation)render(p.projects,c.conversations,a)}catch{if(token===generation)render(initialProjects,initialChats,initialAssets,true)}}
 render(initialProjects,initialChats,initialAssets,true);load();for(const event of ['ceobe:project-updated','ceobe:project-moved','ceobe:project-imported','ceobe:chat-updated'])document.addEventListener(event,load);window.addEventListener('focus',load);
}
