export function initProjectActions(){
 const remove=document.querySelector('[data-project-action-modal=delete]'),renameModal=document.querySelector('[data-project-action-modal=rename]');if(!remove||!renameModal)return;
 const status=document.getElementById('ceobe-chat-status'),prefix=location.pathname.includes('/conversations/')?'../':'./';let active=null,busy=false,inerted=[],editing=null;
 const tell=t=>{if(status){status.textContent=t;status.hidden=false}};
 const changed=result=>document.dispatchEvent(new CustomEvent('ceobe:project-updated',{detail:result}));
 async function post(body){const r=await fetch('/api/projects/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json().catch(()=>null);if(!r.ok||!data)throw Error(data?.error||'本地服务不可用，项目操作未确认成功');return data}
 function lock(root){for(const e of document.body.children)if(e!==root&&!['SCRIPT','LINK','STYLE','TEMPLATE'].includes(e.tagName)){inerted.push([e,e.inert]);e.inert=true}root.hidden=false;root.querySelector('[role=dialog]').dataset.state='open'}
 function close(){if(busy)return;const opener=active?.opener;for(const root of [remove,renameModal]){root.hidden=true;root.querySelector('[role=dialog]').dataset.state='closed'}for(const [e,old] of inerted)e.inert=old;inerted=[];active=null;opener?.focus()}
 function cancelInline(){if(!editing||busy)return;const {container,old,opener}=editing;editing=null;container.replaceChildren(...old);document.body.removeAttribute('data-project-editing');opener?.focus()}
 async function saveName(name){if(busy)return;const project=editing?.project||active?.project;if(!project)return;name=name.trim().normalize('NFC');if(!name||[...name].length>80||/[\x00-\x1f\x7f]/.test(name)){tell('项目名称须为 1–80 个字符');(editing?.input||renameModal.querySelector('input')).focus();return}
 if(name===project.name){if(editing)cancelInline();else close();return}busy=true;const input=editing?.input||renameModal.querySelector('input');input.readOnly=true;
 try{const result=await post({id:project.id,action:'rename',name});busy=false;if(editing)cancelInline();else close();changed(result);tell('项目已重命名。')}catch(e){tell(e.message);if(active)renameModal.querySelector('[role=status]').textContent=e.message;input.focus()}finally{busy=false;input.readOnly=false}
 }
 function inline(project,opener){const container=opener.closest('[data-organizer-project]')?.querySelector('._NCija_content');if(!container)return false;const input=document.getElementById('ceobe-project-inline-rename').content.firstElementChild.cloneNode(true),old=[...container.childNodes];input.value=project.name;editing={container,old,input,project,opener};document.body.dataset.projectEditing='true';container.replaceChildren(input);input.addEventListener('click',e=>e.stopPropagation());input.addEventListener('keydown',e=>{e.stopPropagation();if(e.isComposing)return;if(e.key==='Enter'){e.preventDefault();saveName(input.value)}else if(e.key==='Escape'){e.preventDefault();cancelInline()}});input.addEventListener('blur',()=>saveName(input.value));input.focus();input.select();return true}
 const form=renameModal.querySelector('form'),nameInput=form.querySelector('input');form.addEventListener('submit',e=>{e.preventDefault();saveName(nameInput.value)});renameModal.querySelector('header button').addEventListener('click',close);
 const confirm=remove.querySelector('.btn-danger'),cancel=remove.querySelector('.btn-secondary');cancel.addEventListener('click',close);confirm.addEventListener('click',async()=>{if(busy||!active)return;busy=true;confirm.disabled=cancel.disabled=true;try{const id=active.project.id,result=await post({id,action:'delete',confirm:id});busy=false;close();changed(result);tell('项目已删除；全部聊天、附件和历史归档均保留。');if(document.body.dataset.projectImportId===id||new URLSearchParams(location.search).get('id')===id)location.href=prefix+'projects.html'}catch(e){tell(e.message);remove.querySelector('[data-project-delete-message]').textContent=e.message+' 全部聊天归档保持不变，可重试或取消。'}finally{busy=false;confirm.disabled=cancel.disabled=false}});
 for(const root of [remove,renameModal])root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close()}else if(e.key==='Tab'){const buttons=[...root.querySelectorAll('button:not([disabled]),input:not([disabled])')].filter(e=>e.checkVisibility()),i=buttons.indexOf(document.activeElement);e.preventDefault();buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus()}});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-project-rename-current]');if(b){e.preventDefault();document.dispatchEvent(new CustomEvent('ceobe:project-action',{detail:{id:document.body.dataset.projectImportId,action:'rename',opener:b}}))}});
 document.addEventListener('ceobe:project-action',async e=>{if(active||editing||busy)return;const {id,action,opener}=e.detail;busy=true;try{const r=await fetch('/api/projects',{cache:'no-store'}),data=await r.json().catch(()=>null);if(!r.ok||!data?.writable)throw Error('当前服务只读，无法修改项目');const project=data.projects.find(p=>p.id===id);if(!project)throw Error('项目不存在');busy=false;
 if(action==='pin'){busy=true;const result=await post({id,action,pinned:!project.pinned_at});changed(result);tell(result.project.pinned_at?'项目已置顶。':'已取消项目置顶。')}
 else if(action==='rename'){if(inline(project,opener))return;active={project,opener};nameInput.value=project.name;renameModal.querySelector('[role=status]').textContent='回车保存；Esc 或关闭取消。';const icon=renameModal.querySelector('[data-testid=project-folder-icon]'),source=document.querySelector('#ceobe-chat-icon-bank [data-chat-icon="'+project.icon+'"] use');if(icon&&source){icon.querySelector('use').setAttribute('href',source.getAttribute('href'));icon.style.color=project.color==='default'?'var(--icon-primary)':project.color}lock(renameModal);nameInput.focus();nameInput.select()}
 else if(action==='delete'){active={project,opener};remove.querySelector('h2').textContent='删除“'+project.name+'”？';remove.querySelector('[data-project-delete-message]').textContent='只删除项目及其关联。全部聊天、附件和历史归档均保留，项目中的聊天回到未归属列表。此操作无法撤销。';lock(remove);cancel.focus()}
 }catch(error){tell(error.message)}finally{busy=false}});
}
