import {initProjectActions} from './project-actions.js';
import {saveArchive} from './export-download.js';
export function initProjectMore(){
 initProjectActions();const side=document.querySelector('[data-project-more-popup]'),head=document.querySelector('[data-project-header-popup]');if(!side)return;let active=null;const prefix=location.pathname.includes('/conversations/')?'../':'./',status=document.getElementById('ceobe-chat-status');
 const tell=text=>{status.textContent=text;status.hidden=false};
 function items(){return active?[...active.menu.querySelectorAll('[role=menuitem]')].filter(e=>e.checkVisibility()):[]}
 function highlight(item){for(const e of items())e.toggleAttribute('data-highlighted',e===item)}
 function close(focus=true){if(!active)return;const {wrapper,menu,trigger}=active;highlight(null);wrapper.hidden=true;menu.dataset.state='closed';trigger.dataset.state='closed';trigger.setAttribute('aria-expanded','false');active=null;if(focus)trigger.focus()}
 function open(trigger,keyboard){if(active?.trigger===trigger){close();return}close(false);document.dispatchEvent(new Event('ceobe:close-chat-menu'));document.dispatchEvent(new Event('ceobe:close-organizer'));document.dispatchEvent(new Event('ceobe:close-reader-more'));const id=trigger.dataset.projectMore||document.body.dataset.projectImportId;if(!id)return;const wrapper=trigger.hasAttribute('data-project-more-current')&&head?head:side,menu=wrapper.querySelector('[role=menu]'),layout=JSON.parse(wrapper.dataset.layout);active={wrapper,menu,trigger,id};trigger.dataset.state='open';trigger.setAttribute('aria-expanded','true');trigger.setAttribute('aria-controls',menu.id);if(!trigger.id)trigger.id='project-more-trigger-'+id;menu.setAttribute('aria-labelledby',trigger.id);
 const pin=[...menu.querySelectorAll('[role=menuitem]')].find(e=>e.textContent.includes('置顶项目'));if(pin)for(const n of pin.childNodes)if(n.nodeType===3&&n.textContent.trim())n.textContent=trigger.dataset.projectPinned==='true'?'取消置顶项目':'置顶项目';wrapper.hidden=false;menu.dataset.state='open';const r=trigger.getBoundingClientRect(),s=wrapper.style;s.setProperty('--radix-popper-anchor-width',r.width+'px');s.setProperty('--radix-popper-anchor-height',r.height+'px');s.setProperty('--radix-popper-available-width',innerWidth+'px');s.setProperty('--radix-popper-available-height',Math.max(100,innerHeight-r.bottom-layout.offset.y)+'px');const box=wrapper.getBoundingClientRect(),x=(layout.align==='end'?r.right-box.width:r.left)+layout.offset.x,y=r.bottom+layout.offset.y;s.transform=`translate(${Math.max(0,Math.min(x,innerWidth-box.width))}px,${Math.max(0,Math.min(y,innerHeight-box.height))}px)`;if(keyboard)items()[0]?.focus();else menu.focus({preventScroll:true})}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-project-more],[data-project-more-current]');if(!b)return;e.preventDefault();e.stopPropagation();open(b,e.detail===0)},true);
 for(const wrapper of [side,head].filter(Boolean)){const menu=wrapper.querySelector('[role=menu]');menu.addEventListener('click',e=>{const item=e.target.closest('[role=menuitem]');if(!item||!active)return;const name=item.textContent.trim(),{id,trigger}=active,title=trigger.closest('[data-organizer-project]')?.querySelector('._NCija_content')?.textContent||document.body.dataset.projectImportName||'项目';
 if(name==='另存为 ZIP'){close(false);saveArchive('zip',id,title);return}if(name==='项目主页'){close(false);location.href=prefix+'project.html?id='+encodeURIComponent(id);return}if(name==='项目设置'){close(false);document.dispatchEvent(new CustomEvent('ceobe:project-settings-preview',{detail:{id,opener:trigger}}));return}const action={'重命名项目':'rename','置顶项目':'pin','取消置顶项目':'pin','删除项目':'delete'}[name];if(action){close(false);document.dispatchEvent(new CustomEvent('ceobe:project-action',{detail:{id,opener:trigger,action}}));return}tell('“'+name+'”尚未接入功能，本次未修改项目。')});
 menu.addEventListener('pointermove',e=>highlight(e.target.closest('[role=menuitem]')));menu.addEventListener('pointerleave',()=>highlight(null));menu.addEventListener('focusin',e=>highlight(e.target.closest('[role=menuitem]')));menu.addEventListener('keydown',e=>{const list=items(),i=list.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();list[e.key==='Home'?0:e.key==='End'?list.length-1:i<0?0:(i+(e.key==='ArrowDown'?1:-1)+list.length)%list.length]?.focus()}else if(e.key==='Escape'){e.preventDefault();close()}else if(['Enter',' '].includes(e.key)){e.preventDefault();document.activeElement.closest('[role=menuitem]')?.click()}else if(e.key==='Tab')e.preventDefault()})}
 document.addEventListener('focusin',e=>{if(active&&!active.wrapper.contains(e.target)&&e.target!==active.trigger)close(false)});document.addEventListener('pointerdown',e=>{if(active&&!active.wrapper.contains(e.target)&&!e.target.closest('[data-project-more],[data-project-more-current]'))close(false)});window.addEventListener('resize',()=>close(false));document.addEventListener('scroll',e=>{if(active&&!active.wrapper.contains(e.target))close(false)},true);document.addEventListener('ceobe:close-project-more',()=>close(false));
}
