export function initProjectMore(){
 const wrapper=document.querySelector('[data-project-more-popup]');if(!wrapper)return;
 const layout=JSON.parse(wrapper.dataset.layout);
 const menu=wrapper.querySelector('[role=menu]'),items=[...menu.querySelectorAll('[role=menuitem]')],status=document.getElementById('ceobe-chat-status');let trigger=null,projectId=null;
 const prefix=location.pathname.includes('/conversations/')?'../':'./';
 function highlight(item){for(const e of items)e.toggleAttribute('data-highlighted',e===item)}
 function close(focus=true){wrapper.hidden=true;menu.dataset.state='closed';highlight(null);if(trigger){trigger.dataset.state='closed';trigger.setAttribute('aria-expanded','false');if(focus)trigger.focus()}trigger=null;projectId=null}
 function open(b,keyboard){if(trigger===b){close();return}close(false);document.dispatchEvent(new Event('ceobe:close-chat-menu'));document.dispatchEvent(new Event('ceobe:close-organizer'));trigger=b;projectId=b.dataset.projectMore||document.body.dataset.projectImportId;if(!projectId){close(false);return}b.dataset.state='open';b.setAttribute('aria-expanded','true');b.setAttribute('aria-controls',menu.id);if(!b.id)b.id='project-more-trigger-'+projectId;menu.setAttribute('aria-labelledby',b.id);wrapper.hidden=false;menu.dataset.state='open';const r=b.getBoundingClientRect(),s=wrapper.style;s.setProperty('--radix-popper-anchor-width',r.width+'px');s.setProperty('--radix-popper-anchor-height',r.height+'px');s.setProperty('--radix-popper-available-width',innerWidth+'px');s.setProperty('--radix-popper-available-height',Math.max(100,innerHeight-(r.bottom+layout.offset.y))+'px');s.transform=`translate(${r.left+layout.offset.x}px, ${r.bottom+layout.offset.y}px)`;const box=wrapper.getBoundingClientRect();s.transform=`translate(${Math.max(0,Math.min(r.left+layout.offset.x,innerWidth-box.width))}px, ${Math.max(0,Math.min(r.bottom+layout.offset.y,innerHeight-box.height))}px)`;if(keyboard)items[0].focus();else menu.focus({preventScroll:true})}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-project-more],[data-project-more-current]');if(!b)return;e.preventDefault();e.stopPropagation();open(b,e.detail===0)},true);
 menu.addEventListener('click',e=>{const item=e.target.closest('[role=menuitem]');if(!item)return;const name=item.textContent.trim();if(name==='项目主页'){const id=projectId;close(false);location.href=prefix+'project.html?id='+encodeURIComponent(id);return}if(status){status.textContent='“'+name+'”尚未接入功能，本次未修改项目。';status.hidden=false}});
 menu.addEventListener('pointermove',e=>highlight(e.target.closest('[role=menuitem]')));menu.addEventListener('pointerleave',()=>highlight(null));menu.addEventListener('focusin',e=>highlight(e.target.closest('[role=menuitem]')));
 menu.addEventListener('keydown',e=>{const i=items.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();items[e.key==='Home'?0:e.key==='End'?items.length-1:i<0?0:(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length].focus()}else if(e.key==='Escape'){e.preventDefault();close()}else if(e.key==='Enter'||e.key===' '){e.preventDefault();document.activeElement.closest('[role=menuitem]')?.click()}else if(e.key==='Tab')close(false)});
 document.addEventListener('focusin',e=>{if(trigger&&!wrapper.contains(e.target)&&e.target!==trigger)close(false)});
 document.addEventListener('pointerdown',e=>{if(!wrapper.contains(e.target)&&!e.target.closest('[data-project-more],[data-project-more-current]'))close(false)});window.addEventListener('resize',()=>close(false));document.addEventListener('scroll',e=>{if(!wrapper.contains(e.target))close(false)},true);document.addEventListener('ceobe:close-project-more',()=>close(false));
}
