import {initProjectAppearance} from './project-appearance.js';
import {saveArchive} from './export-download.js';
(() => {
 const id=document.body.dataset.readerChatId,trigger=document.querySelector('[data-reader-more]'),wrapper=document.querySelector('[data-reader-menu]'),menu=wrapper?.querySelector('[role=menu]'),sub=document.querySelector('[data-reader-move]'),subMenu=sub?.querySelector('[role=menu]'),settings=document.querySelector('[data-project-settings-preview]'),picker=settings?.querySelector('[data-preview-picker]'),viewer=document.querySelector('[data-reader-image-viewer]');
 const status=document.getElementById('ceobe-chat-status');let moveGeneration=0,moving=false,active=null,inerted=[],lastFocus=null,oldOverflow='',project=null,imageGeneration=0,currentImage=null;
 const tell=text=>{if(status){status.textContent=text;status.hidden=false}};
 const rows=panel=>[...panel.querySelectorAll('[role=menuitem],[role=menuitemradio]')].filter(e=>e.checkVisibility());
 const highlight=(panel,item)=>{for(const e of rows(panel))e.toggleAttribute('data-highlighted',e===item)};
 function closeSub(){moveGeneration++;if(sub){sub.hidden=true;subMenu.dataset.state='closed';const anchor=menu.querySelector('[data-reader-action=move]');anchor.setAttribute('aria-expanded','false');anchor.dataset.state='closed'}}
 function closeReader(focus=false){closeSub();if(wrapper){wrapper.hidden=true;menu.dataset.state='closed';trigger?.setAttribute('aria-expanded','false');highlight(menu,null);if(focus)trigger?.focus()}}
 function placeMenu(){const layout=JSON.parse(wrapper.dataset.layout),r=trigger.getBoundingClientRect(),s=wrapper.style;s.setProperty('--radix-popper-anchor-width',r.width+'px');s.setProperty('--radix-popper-anchor-height',r.height+'px');s.setProperty('--radix-popper-available-height',Math.max(100,innerHeight-r.bottom-layout.offset.y)+'px');const b=wrapper.getBoundingClientRect();s.transform=`translate(${Math.max(0,Math.min(r.right-b.width+layout.offset.x,innerWidth-b.width))}px,${Math.max(0,Math.min(r.bottom+layout.offset.y,innerHeight-b.height))}px)`}
 function openReader(keyboard){if(!wrapper.hidden){closeReader(true);return}document.dispatchEvent(new Event('ceobe:close-chat-menu'));document.dispatchEvent(new Event('ceobe:close-project-more'));document.dispatchEvent(new Event('ceobe:close-organizer'));wrapper.hidden=false;menu.dataset.state='open';trigger.setAttribute('aria-expanded','true');const pinned=document.querySelector('[data-ceobe-chat-id="'+id+'"]')?.dataset.chatPinned==='true',item=menu.querySelector('[data-reader-action=pin]');for(const n of item.childNodes)if(n.nodeType===3&&n.textContent.trim())n.textContent=pinned?'取消置顶聊天':'置顶聊天';placeMenu();(keyboard?rows(menu)[0]:menu).focus({preventScroll:true})}
 function positionSub(){const anchor=menu.querySelector('[data-reader-action=move]'),r=anchor.getBoundingClientRect(),layout=JSON.parse(sub.dataset.layout),s=sub.style;s.setProperty('--radix-popper-anchor-width',r.width+'px');s.setProperty('--radix-popper-anchor-height',r.height+'px');s.setProperty('--radix-popper-available-height',innerHeight+'px');const b=sub.getBoundingClientRect(),gap=Math.abs(layout.offset.x),left=r.right+gap+b.width>innerWidth;subMenu.dataset.side=left?'left':'right';const x=left?r.left-b.width-gap:r.right+gap,y=r.top+layout.offset.y;s.transform=`translate(${Math.max(0,Math.min(x,innerWidth-b.width))}px,${Math.max(0,Math.min(y,innerHeight-b.height))}px)`}
 async function openMove(focus=false){const token=++moveGeneration,list=sub.querySelector('[data-reader-project-list]'),anchor=menu.querySelector('[data-reader-action=move]');for(const row of list.querySelectorAll('[data-reader-project-row]'))row.remove();sub.hidden=false;subMenu.dataset.state='open';anchor.dataset.state='open';anchor.setAttribute('aria-expanded','true');positionSub();if(focus)rows(subMenu)[0]?.focus();try{const r=await fetch('/api/projects',{cache:'no-store'}),data=await r.json();if(!r.ok||!data.writable)throw Error('当前服务不可写，无法移至项目');if(token!==moveGeneration)return;for(const [index,p] of data.projects.entries()){const row=document.getElementById('ceobe-reader-project-row').content.firstElementChild.cloneNode(true);row.dataset.readerProjectRow='';if(index)row.querySelector('[role=separator]')?.remove();const item=row.querySelector('[role=menuitem]');item.dataset.readerProject=p.id;item.tabIndex=-1;row.querySelector('.truncate').textContent=p.name;const box=row.querySelector('[data-testid=project-folder-icon]'),icon=[...document.querySelectorAll('#ceobe-chat-icon-bank [data-chat-icon]')].find(e=>e.dataset.chatIcon===p.icon);if(box&&icon){box.querySelector('svg').replaceWith(icon.cloneNode(true));box.style.color=p.color==='default'?'var(--icon-primary)':p.color}list.append(row)}positionSub()}catch(e){tell(e.message)}}
 trigger?.addEventListener('click',e=>{e.preventDefault();openReader(e.detail===0)});
 menu?.addEventListener('click',e=>{const item=e.target.closest('[data-reader-action]');if(!item)return;const action=item.dataset.readerAction;if(action==='move'){openMove(true);return}closeReader();if(action==='md')saveArchive('md',id,document.title);else if(['pin','delete'].includes(action))document.dispatchEvent(new CustomEvent('ceobe:chat-action',{detail:{id,opener:trigger,action}}));else if(action==='files'){const panel=document.querySelector('[data-ceobe-sources-panel]');if(panel){document.dispatchEvent(new Event('ceobe:open-sources'))}else tell('当前聊天没有可用的本地文件和来源面板。')}});
 const moveItem=menu?.querySelector('[data-reader-action=move]');moveItem?.addEventListener('pointerenter',()=>{if(sub.hidden)openMove()});menu?.addEventListener('pointerover',e=>{if(e.target.closest('[data-reader-action]')!==moveItem)closeSub()});
 sub?.addEventListener('click',async e=>{if(moving)return;const create=e.target.closest('[data-reader-new-project]');if(create){closeReader();document.dispatchEvent(new CustomEvent('ceobe:open-project',{detail:{opener:trigger,conversationId:id}}));return}const item=e.target.closest('[data-reader-project]');if(!item||moving)return;moving=true;try{const r=await fetch('/api/projects/move',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversationId:id,projectId:item.dataset.readerProject})}),data=await r.json();if(!r.ok)throw Error(data.error||'移动失败');closeReader(true);document.dispatchEvent(new Event('ceobe:project-moved'));tell('已移至“'+data.project.name+'”。原始聊天归档保持不变。')}catch(err){tell(err.message)}finally{moving=false}});
 for(const panel of [menu,subMenu].filter(Boolean)){panel.addEventListener('pointermove',e=>highlight(panel,e.target.closest('[role=menuitem]')));panel.addEventListener('focusin',e=>highlight(panel,e.target.closest('[role=menuitem]')));panel.addEventListener('keydown',e=>{const list=rows(panel),i=list.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();list[e.key==='Home'?0:e.key==='End'?list.length-1:i<0?0:(i+(e.key==='ArrowDown'?1:-1)+list.length)%list.length]?.focus()}else if(e.key==='ArrowRight'&&document.activeElement===moveItem){e.preventDefault();openMove(true)}else if((e.key==='ArrowLeft'||e.key==='Escape')&&panel===subMenu){e.preventDefault();closeSub();moveItem.focus()}else if(e.key==='Escape'){e.preventDefault();closeReader(true)}else if(e.key==='Tab')e.preventDefault();else if(['Enter',' '].includes(e.key)){e.preventDefault();document.activeElement.closest('[role=menuitem]')?.click()}})}
 document.addEventListener('ceobe:close-reader-more',()=>closeReader());document.addEventListener('pointerdown',e=>{if(wrapper&&!wrapper.contains(e.target)&&!sub.contains(e.target)&&!e.target.closest('[data-reader-more]'))closeReader()});document.addEventListener('focusin',e=>{if(wrapper&&!wrapper.hidden&&!wrapper.contains(e.target)&&!sub.contains(e.target)&&e.target!==trigger)closeReader()});document.addEventListener('scroll',e=>{if(wrapper&&!wrapper.hidden&&!wrapper.contains(e.target)&&!sub.contains(e.target))closeReader()},true);
 function closeModal(){if(!active||active===settings&&(descriptionSaving||appearance.isSaving()))return;if(picker?.open)picker.close();active.hidden=true;active.dataset.state='closed';const dialog=active.querySelector('[role=dialog]');if(dialog)dialog.dataset.state='closed';for(const [e,was] of inerted)e.inert=was;inerted=[];document.body.style.overflow=oldOverflow;active=null;currentImage=null;(lastFocus?.isConnected?lastFocus:[...document.querySelectorAll('[data-project-more]')].find(b=>b.dataset.projectMore===project?.id)||document.querySelector('[data-project-more-current]'))?.focus()}
 function openModal(root,opener){closeModal();closeReader();document.dispatchEvent(new Event('ceobe:close-project-more'));document.dispatchEvent(new Event('ceobe:close-chat-menu'));lastFocus=opener;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';for(const e of document.body.children)if(e!==root&&!['SCRIPT','LINK','STYLE','TEMPLATE'].includes(e.tagName)){inerted.push([e,e.inert]);e.inert=true}active=root;root.hidden=false;root.dataset.state='open';root.querySelector('[role=dialog]')?.setAttribute('data-state','open')}
 function fitImage(){if(!currentImage||!viewer)return;const img=viewer.querySelector('img'),w=currentImage.naturalWidth||currentImage.width,h=currentImage.naturalHeight||currentImage.height,scale=Math.min(1,innerWidth*.9/w,innerHeight*.85/h);img.parentElement.style.width=w*scale+'px';img.parentElement.style.height=h*scale+'px';img.parentElement.style.aspectRatio=w+'/'+h}
 async function openImage(opener){const source=opener.matches('img')?opener:opener.querySelector('img');if(!source)return;const token=++imageGeneration;try{const url=new URL(source.currentSrc||source.src,location.href);if(url.origin!==location.origin&&!url.href.startsWith('data:image/'))throw Error('只查看已保存在本地的图片');await source.decode();if(token!==imageGeneration)return;const img=viewer.querySelector('img');img.loading='eager';img.src=url.href;img.alt=source.alt||'图片';openModal(viewer,opener);currentImage=source;fitImage();viewer.querySelector('[data-image-close]').focus()}catch(e){tell('图片无法打开：'+e.message)}}
 viewer?.addEventListener('click',e=>{if(e.target===viewer||e.target.closest('[data-image-close]'))closeModal()});
 document.addEventListener('click',e=>{const save=e.target.closest('[data-reader-save]');if(save){e.preventDefault();saveArchive('md',id,document.title);return}const zip=e.target.closest('[data-project-export]');if(zip){e.preventDefault();saveArchive('zip',document.body.dataset.projectImportId,document.body.dataset.projectImportName);return}const image=e.target.closest('[data-reader-image-open]');if(image){e.preventDefault();openImage(image)}});
 document.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('img[data-reader-image-open]')){e.preventDefault();openImage(e.target)}});
 // Project description is a local, explicitly saved field; closing discards an unsaved draft.
 const description=settings?.querySelector('[data-project-description]'),descriptionSave=settings?.querySelector('[data-description-save]'),descriptionStatus=settings?.querySelector('[data-description-status]');let settingsWritable=false,descriptionSaving=false,savedDescription='',settingsGeneration=0;
 function updateDescription(){if(!description)return;description.readOnly=!settingsWritable||descriptionSaving;descriptionSave.disabled=!settingsWritable||descriptionSaving||description.value===savedDescription;for(const b of settings.querySelectorAll('[data-preview-close],[data-preview-delete],[data-preview-icon]'))b.disabled=descriptionSaving}
 description?.addEventListener('input',()=>{updateDescription();descriptionStatus.textContent=description.value===savedDescription?'简介未修改。':'有未保存的修改；点击“保存简介”生效，关闭或 Esc 取消。';description.removeAttribute('aria-invalid')});
 async function saveDescription(){if(descriptionSaving||!settingsWritable||!project||description.value===savedDescription)return;const text=description.value;if(text.length>4000){description.setAttribute('aria-invalid','true');descriptionStatus.textContent='项目简介不能超过 4000 个字符。';return}descriptionSaving=true;updateDescription();descriptionStatus.textContent='正在保存项目简介…';try{const r=await fetch('/api/projects/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:project.id,action:'description',description:text,previousDescription:savedDescription}),signal:AbortSignal.timeout(30000)}),data=await r.json().catch(()=>null);if(!r.ok||typeof data?.project?.description!=='string')throw Error(data?.error||'项目简介保存失败，请重试');project=data.project;savedDescription=project.description;description.value=savedDescription;settings.querySelector('input').value=project.name;descriptionStatus.textContent='项目简介已保存到本地。';document.dispatchEvent(new CustomEvent('ceobe:project-updated',{detail:data}))}catch(e){descriptionStatus.textContent='保存失败：'+e.message+'。当前草稿仍保留，可复制后关闭或重试。'}finally{descriptionSaving=false;updateDescription();if(active===settings)description.focus({preventScroll:true})}}
 descriptionSave?.addEventListener('click',saveDescription);
 const appearance=initProjectAppearance({settings,picker,getProject:()=>project,isWritable:()=>settingsWritable,isBusy:()=>descriptionSaving,onSaved:result=>{project=result.project;settings.querySelector('input').value=project.name;document.dispatchEvent(new CustomEvent('ceobe:project-updated',{detail:result}))}});
 document.addEventListener('ceobe:project-settings-preview',async e=>{if(active===settings){description?.focus();return}const generation=++settingsGeneration;try{let data,offline=false;try{const r=await fetch('/api/projects',{cache:'no-store'});data=await r.json();if(!r.ok||!Array.isArray(data.projects))throw Error()}catch{offline=true;data={projects:JSON.parse(document.getElementById('ceobe-projects-data').textContent),writable:false}}if(generation!==settingsGeneration)return;project=data.projects.find(p=>p.id===e.detail.id);if(!project)throw Error('项目不存在或已删除');settingsWritable=data.writable===true&&!offline;settings.querySelector('input').value=project.name;savedDescription=typeof project.description==='string'?project.description:'';description.value=savedDescription;description.removeAttribute('aria-invalid');descriptionStatus.textContent=settingsWritable?'点击“保存简介”生效；关闭或 Esc 取消未保存的修改。':offline?'当前是只读快照，简介可能不是最新，无法保存。':'当前服务只读，无法保存项目简介。';updateDescription();settings.querySelector('[data-preview-status]').textContent='名称请通过项目标题或重命名菜单修改；图标和颜色在选择器中点击“完成”保存。删除项目保留全部聊天。';const box=settings.querySelector('[data-testid=project-folder-icon]'),icon=[...document.querySelectorAll('#ceobe-chat-icon-bank [data-chat-icon]')].find(x=>x.dataset.chatIcon===project.icon);if(box&&icon){box.replaceChildren(icon.cloneNode(true));box.style.color=project.color==='default'?'var(--icon-primary)':project.color}openModal(settings,e.detail.opener);settings.querySelector('[data-preview-close]').focus()}catch(error){tell(error.message)}});
 settings?.querySelector('form')?.addEventListener('submit',e=>e.preventDefault());
 settings?.addEventListener('click',e=>{if(e.target.closest('[data-preview-close]')){closeModal();return}if(e.target.closest('[data-preview-delete]')){if(descriptionSaving)return;const detail={id:project.id,opener:lastFocus,action:'delete'};closeModal();document.dispatchEvent(new CustomEvent('ceobe:project-action',{detail}));return}if(e.target.closest('[data-preview-icon]'))appearance.open()});
 for(const root of [settings,viewer].filter(Boolean))root.addEventListener('keydown',e=>{if(picker?.open&&picker.contains(e.target))return;if(e.key==='Escape'){e.preventDefault();closeModal()}else if(e.key==='Tab'){e.preventDefault();const stops=[...root.querySelectorAll('button:not([disabled]),input,textarea,[tabindex]')].filter(el=>el.checkVisibility()&&el.tabIndex>=0),i=stops.indexOf(document.activeElement);stops[(i+(e.shiftKey?-1:1)+stops.length)%stops.length]?.focus()}});
 window.addEventListener('resize',()=>{closeReader();fitImage()});
})();
